version: 2.1

executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest

jobs:
  
  build: 
    executor: ci-executor
    steps:
      - checkout
      - run:
          name: build dependencies
          command: bundle install
      - run:
          name: build the jekyll site #to generate a static site using your text written in your favorite markup language
          command: bundle exec jekyll build
      - run:
          name: notify build is finished
          command: echo "The build is finished!"

  test2: #add testing job
    executor: ci-executor
    steps:
      - checkout
      - run:
          name: build-2 dependencies
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: build-2 the jekyll site #to generate a static site using your text written in your favorite markup language
          command: bundle exec jekyll build
      - run:
          name: notify build-2 is finished
          command: echo "The build-2 is finished!"
      #add more test command
      - run:
          name: run html proofer #to test for any broken links
          command: bundle exec htmlproofer ./_site --check-html
      - run:
          name: notify test is finished
          command: echo "The test is finished!"

  workflows:
    version: 2.1

    build_and_test:
      jobs:
        - build
        - test:
          requires:
            - build